---
- name: Ensure cloudflare pagerules are batched
  tags:
    - pagerules
  ansible.builtin.include_tasks:
    apply:
      tags:
        - pagerules
    file: include.yml
  loop:
    "{{ pagerules_list |
        batch(pagerules_batch) }}"
  loop_control:
    label: "{{ __pagerules_list | length }}"
    loop_var: __pagerules_list
...
