---
- name: Ensure cloudflare access apps are batched
  tags:
    - access_apps
  ansible.builtin.include_tasks:
    apply:
      tags:
        - access_apps
    file: include.yml
  loop:
    "{{ access_apps_list |
        batch(access_apps_batch) }}"
  loop_control:
    label: "{{ __access_apps_list | length }}"
    loop_var: __access_apps_list
...
