---
- name: Ensure cloudflare devices settings are managed
  tags:
    - devices_settings
  linuxhq.cloudflare.devices_settings:
    account_id: "{{ devices_settings_account_id }}"
    api_token: "{{ devices_settings_api_token }}"
    disable_for_time:
      "{{ devices_settings_disable_for_time or omit }}"
    gateway_proxy_enabled:
      "{{ devices_settings_gateway_proxy_enabled or omit }}"
    gateway_udp_proxy_enabled:
      "{{ devices_settings_gateway_udp_proxy_enabled or omit }}"
    root_certificate_installation_enabled:
      "{{ devices_settings_root_certificate_installation_enabled or omit }}"
    use_zt_virtual_ip:
      "{{ devices_settings_use_zt_virtual_ip }}"
  when:
    - devices_settings_account_id is not none
    - devices_settings_api_token is not none
...
