---
- name: Ensure cloudflare cfd tunnel configurations resources are batched
  tags:
    - cfd_tunnel_configurations
  ansible.builtin.include_tasks:
    apply:
      tags:
        - cfd_tunnel_configurations
    file: include.yml
  loop:
    "{{ cfd_tunnel_configurations_list |
        batch(cfd_tunnel_configurations_batch) }}"
  loop_control:
    label: "{{ __cfd_tunnel_configurations_list | length }}"
    loop_var: __cfd_tunnel_configurations_list
...
