---
allow_duplicates: true
dependencies:
  - { role: linuxhq.cloudflare.account_info, tags: service_token_info }
galaxy_info:
  role_name: service_token_info
  author: Taylor Kimball
  description: Gather information about cloudflare service tokens
  license: GPLv3
  min_ansible_version: 2.15.0
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - info
    - service
    - token
...
