---
- name: Ensure cloudflare rules lists resources are batched
  tags:
    - rules_lists
  ansible.builtin.include_tasks:
    apply:
      tags:
        - rules_lists
    file: include.yml
  loop:
    "{{ rules_lists_list |
        batch(rules_lists_batch) }}"
  loop_control:
    label: "{{ __rules_lists_list | length }}"
    loop_var: __rules_lists_list
...
