---
authors:
  - Taylor Kimball (https://github.com/tkimball83)
build_ignore:
  - .ansible-lint
  - .gitignore
  - .yamllint
description: A collection of cloudflare roles
dependencies:
  community.general: '>=8.0.0'
documentation: https://github.com/linuxhq/ansible-collection-cloudflare/blob/main/README.md
homepage: https://www.linuxhq.org
issues: https://github.com/linuxhq/ansible-collection-cloudflare/issues
license:
  - GPL-3.0-or-later
name: cloudflare
namespace: linuxhq
readme: README.md
repository: https://github.com/linuxhq/ansible-collection-cloudflare
tags:
  - cloudflare
  - infrastructure
version: 1.1.8
...
