---
- name: Ensure cloudflare service token details are gathered
  tags:
    - service_token_info
  ansible.builtin.uri:
    follow_redirects: false
    headers:
      Authorization: "Bearer {{ cf_auth_token }}"
    method: GET
    status_code:
      - 200
    url: "{{ 'https://api.cloudflare.com/client/v4/accounts/' +
             cf_account_id +
             '/access/service_tokens' }}"
  register: _service_tokens_get
  when:
    - cf_account_id is not none
    - cf_auth_token is not none

- name: Ensure dictionary of service tokens is generated
  tags:
    - service_token_info
  ansible.builtin.set_fact:
    _cf_service_token_duration: "{{ _cf_service_token_duration |
                                    default({}) |
                                    combine({_name: _duration}) }}"
    _cf_service_token_id: "{{ _cf_service_token_id |
                              default({}) |
                              combine({_name: _id}) }}"
  loop: "{{ _service_tokens_get.json.result }}"
  loop_control:
    label: "{{ _name | default(none) }}"
    loop_var: _token
  vars:
    _id: "{{ _token.id }}"
    _name: "{{ _token.name }}"
    _duration: "{{ _token.duration | default(none) }}"
  when:
    - _service_tokens_get.json.result is defined
    - _service_tokens_get.json.result | length > 0
    - _token.id is defined
    - _token.name is defined
...
