---
- name: Ensure cloudflare access identity providers information is gathered
  tags:
    - access_identity_providers_info
  linuxhq.cloudflare.access_identity_providers_info:
    account_id: "{{ access_identity_providers_info_account_id }}"
    api_token: "{{ access_identity_providers_info_api_token }}"
  register: __access_identity_providers_info_query
  when:
    - access_identity_providers_info_account_id is not none
    - access_identity_providers_info_api_token is not none

- name: Ensure list of cloudflare access identity providers information is generated
  tags:
    - access_identity_providers_info
  ansible.builtin.set_fact:
    _access_identity_providers_info_list:
      "{{ __access_identity_providers_info_query.access_identity_providers |
          d([]) }}"

- name: Ensure dict of cloudflare access identity providers information is generated
  tags:
    - access_identity_providers_info
  ansible.builtin.set_fact:
    _access_identity_providers_info_dict:
      "{{ (dict(_access_identity_providers_info_list |
               json_query('[].type') |
               zip(_access_identity_providers_info_list))) |
          d({}) }}"
...
