---
- name: Ensure cloudflare access identity providers information is gathered
  tags:
    - access_identity_providers_info
  ansible.builtin.uri:
    headers:
      Authorization: "Bearer {{ access_identity_providers_info_api_token }}"
    method: GET
    status_code:
      - 200
    url:
      "{{ 'https://api.cloudflare.com/client/v4/accounts/' ~
          access_identity_providers_info_account_id ~
          '/access/identity_providers' }}"
  register: __access_identity_providers_info_query
  check_mode: false
  when:
    - access_identity_providers_info_account_id is not none
    - access_identity_providers_info_api_token is not none

- name: Ensure list of cloudflare access identity providers information is generated
  tags:
    - access_identity_providers_info
  ansible.builtin.set_fact:
    _access_identity_providers_info_list:
      "{{ __access_identity_providers_info_query.json.result |
          d([]) }}"

- name: Ensure dict of cloudflare access identity providers information is generated
  tags:
    - access_identity_providers_info
  ansible.builtin.set_fact:
    _access_identity_providers_info_dict:
      "{{ (dict(_access_identity_providers_info_list |
               json_query('[].type') |
               zip(_access_identity_providers_info_list))) |
          d({}) }}"
...
