---
- name: Initialize tunnel_info return variables
  tags:
    - tunnel_info
  ansible.builtin.set_fact:
    _cf_tunnel_account_tag: {}
    _cf_tunnel_connections: {}
    _cf_tunnel_id: {}
    _cf_tunnel_remote_config: {}
    _cf_tunnel_status: {}
    _cf_tunnel_type: {}
    _cf_tunnel_token: {}

- name: Ensure cloudflare tunnel details are gathered
  tags:
    - tunnel_info
  ansible.builtin.uri:
    body_format: json
    follow_redirects: false
    headers:
      Authorization: "Bearer {{ cf_auth_token }}"
    method: GET
    status_code:
      - 200
      - 401
      - 403
    url: "{{ 'https://api.cloudflare.com/client/v4/accounts/' +
             cf_account_id +
             '/cfd_tunnel?is_deleted=false' }}"
  register: _tunnels
  when:
    - cf_account_id is not none
    - cf_auth_token is not none

- name: Ensure dictionary of cloudflare tunnels is generated
  tags:
    - tunnel_info
  ansible.builtin.set_fact:
    _cf_tunnel_account_tag: "{{ _cf_tunnel_account_tag |
                                combine({_name: _account_tag}) }}"
    _cf_tunnel_connections: "{{ _cf_tunnel_connections |
                                combine({_name: _connections}) }}"
    _cf_tunnel_id: "{{ _cf_tunnel_id |
                       combine({_name: _id}) }}"
    _cf_tunnel_remote_config: "{{ _cf_tunnel_remote_config |
                                  combine({_name: _remote_config}) }}"
    _cf_tunnel_status: "{{ _cf_tunnel_status |
                           combine({_name: _status}) }}"
    _cf_tunnel_type: "{{ _cf_tunnel_type |
                         combine({_name: _type}) }}"
  loop: "{{ _tunnels.json.result | d([], true) }}"
  loop_control:
    label: "{{ _tunnel.name | default(none) }}"
    loop_var: _tunnel
  vars:
    _id: "{{ _tunnel.id }}"
    _name: "{{ _tunnel.name }}"
    _account_tag: "{{ _tunnel.account_tag | default(none) }}"
    _connections: "{{ _tunnel.connections | default([]) }}"
    _remote_config: "{{ _tunnel.remote_config | default(none) }}"
    _status: "{{ _tunnel.status | default(none) }}"
    _type: "{{ _tunnel.tun_type | default(none) }}"
  when:
    - _tunnel.account_tag is defined
    - _tunnel.id is defined
    - _tunnel.name is defined

- name: Fetch tunnel tokens if requested
  tags:
    - tunnel_info
  block:
    - name: "Determine target tunnels for token fetching"
      ansible.builtin.set_fact:
        _target_tunnels_for_tokens: "{{ (cf_tunnel_names is defined and cf_tunnel_names | length > 0) | ternary(_cf_tunnel_id | dict2items | selectattr('key', 'in', cf_tunnel_names) | items2dict, _cf_tunnel_id) }}"

    - name: "Ensure cloudflare tunnel tokens are gathered"
      ansible.builtin.uri:
        body_format: json
        follow_redirects: false
        headers:
          Authorization: "Bearer {{ cf_auth_token }}"
        method: GET
        status_code: 200
        url: "{{ 'https://api.cloudflare.com/client/v4/accounts/' + cf_account_id + '/cfd_tunnel/' + item + '/token' }}"
      register: _tokens
      loop: "{{ _target_tunnels_for_tokens.values() | list }}"
      loop_control:
        label: "{{ item }}"

    - name: "Ensure dict of cloudflare tunnel tokens is generated"
      ansible.builtin.set_fact:
        _cf_tunnel_token: "{{ _cf_tunnel_token | combine({ item[0]: item[1] }) }}"
      loop: "{{ _target_tunnels_for_tokens.keys() | list | zip(_tokens.results | map(attribute='json.result')) | list }}"
      loop_control:
        label: "{{ item.0 }}"
  when: cf_fetch_tunnel_token
