---
- name: Ensure cloudflare tunnel details are gathered
  tags:
    - tunnel_info
  ansible.builtin.uri:
    body:
      is_deleted: 'false'
    body_format: json
    follow_redirects: false
    headers:
      Authorization: "Bearer {{ cf_auth_token }}"
    method: GET
    status_code:
      - 200
    url: "{{ 'https://api.cloudflare.com/client/v4/accounts/' +
             cf_account_id +
             '/cfd_tunnel' }}"
  register: _tunnels
  when:
    - cf_account_id is not none
    - cf_auth_token is not none

- name: Ensure dictionary of cloudflare tunnels is generated
  tags:
    - tunnel_info
  ansible.builtin.set_fact:
    _cf_tunnel_account_tag: "{{ _cf_tunnel_account_tag |
                                default({}) |
                                combine({_name: _account_tag}) }}"
    _cf_tunnel_id: "{{ _cf_tunnel_id |
                       default({}) |
                       combine({_name: _id}) }}"
  loop: "{{ _tunnels.json.result }}"
  loop_control:
    label: "{{ _tunnel.name | default(none) }}"
    loop_var: _tunnel
  vars:
    _account_tag: "{{ _tunnel.account_tag }}"
    _id: "{{ _tunnel.id }}"
    _name: "{{ _tunnel.name }}"
  when:
    - _tunnels.json.result is defined
    - _tunnel.account_tag is defined
    - _tunnel.id is defined
    - _tunnel.name is defined
...
