---
- name: Ensure cloudflare application details are gathered
  tags:
    - application_info
  ansible.builtin.uri:
    follow_redirects: false
    headers:
      Authorization: "Bearer {{ cf_auth_token }}"
    method: GET
    status_code:
      - 200
    url: "{{ 'https://api.cloudflare.com/client/v4/accounts/' +
             cf_account_id +
             '/access/apps' }}"
  register: _apps_get
  when:
    - cf_account_id is not none
    - cf_auth_token is not none

- name: Ensure dictionary of application ids is generated
  tags:
    - application_info
  ansible.builtin.set_fact:
    _cf_application_id: "{{ _cf_application_id |
                            default({}) |
                            combine({_name: _id}) }}"
  loop: "{{ _apps_get.json.result }}"
  loop_control:
    label: "{{ _name | default(none) }}"
    loop_var: _app
  vars:
    _name: "{{ _app.name }}"
    _id: "{{ _app.id }}"
  when:
    - _apps_get.json.result is defined
    - _apps_get.json.result | length > 0
    - _app.id is defined
    - _app.name is defined
...
