---
- name: Converge
  hosts: all
  roles:
    - role: zones
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: purge_cache
      purge_cache_list: []
      tags:
        - molecule-idempotence-notest

    - purge_cache
...
