---
- name: Ensure cloudflare access policies are batched
  tags:
    - access_policies
  ansible.builtin.include_tasks:
    apply:
      tags:
        - access_policies
    file: include.yml
  loop:
    "{{ access_policies_list |
        batch(access_policies_batch) }}"
  loop_control:
    label: "{{ __access_policies_list | length }}"
    loop_var: __access_policies_list
...
