---
dependencies: []
galaxy_info:
  role_name: rule_list
  author: Taylor Kimball
  description: Create and update cloudflare rule lists
  license: GPLv3
  min_ansible_version: 2.14.0
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - cloudflare
    - list
    - rule
...
