---
- name: Ensure cloudflare access service tokens are batched
  tags:
    - access_service_tokens
  ansible.builtin.include_tasks:
    apply:
      tags:
        - access_service_tokens
    file: include.yml
  loop:
    "{{ access_service_tokens_list |
        batch(access_service_tokens_batch) }}"
  loop_control:
    label: "{{ __access_service_tokens_list | length }}"
    loop_var: __access_service_tokens_list
...
