---
- name: Ensure cloudflare pages projects are batched
  tags:
    - pages_projects
  ansible.builtin.include_tasks:
    apply:
      tags:
        - pages_projects
    file: include.yml
  loop:
    "{{ pages_projects_list |
        batch(pages_projects_batch) }}"
  loop_control:
    label: "{{ __pages_projects_list | length }}"
    loop_var: __pages_projects_list
...
