---
cfd_tunnel_configurations_account_id: "{{ _accounts_info_id }}"
cfd_tunnel_configurations_api_token: "{{ cloudflare_api_token }}"

cfd_tunnel_configurations_info_account_id: "{{ _accounts_info_id }}"
cfd_tunnel_configurations_info_api_token: "{{ cloudflare_api_token }}"

cfd_tunnel_configurations_list:
  - tunnel_id: "{{ _cfd_tunnel_info_dict[cloudflare_domain ~ '-remote'].id }}"
    config:
      ingress:
        - hostname: remote.linuxhq.dev
          originRequest:
            http2Origin: true
            originServerName: remote.linuxhq.dev
          service: https://nginx:8443
        - service: http_status:404
...
