---
- name: Verify
  hosts: all

  roles:
    - cfd_tunnel_info
    - cfd_tunnel_configurations_info

  post_tasks:
    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _cfd_tunnel_configurations_info_dict['molecule'].config.ingress.0.hostname ==
              cfd_tunnel_configurations_list.0.config.ingress.0.hostname
          - _cfd_tunnel_configurations_info_dict['molecule'].config.ingress.1.hostname ==
              cfd_tunnel_configurations_list.0.config.ingress.1.hostname

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        cfd_tunnel_list:
          "{{ cfd_tunnel_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - cfd_tunnel
      loop_control:
        label: "{{ _role | d(none) }}"
        loop_var: _role
...
