---
dependencies:
  - { role: linuxhq.cloudflare.zone_info, tags: application }
galaxy_info:
  role_name: application
  author: Taylor Kimball
  description: Create cloudflare access application
  license: GPLv3
  min_ansible_version: 2.15.0
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - application
    - cloudflare
...
