---
allow_duplicates: true
dependencies:
  - role: account_info
    tags: tunnel_info
galaxy_info:
  role_name: tunnel_info
  author: Taylor Kimball
  description: Gather information about cloudflare tunnels
  license: GPLv3
  min_ansible_version: 2.15.0
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - info
    - tunnel
...
