---
- name: Ensure cloudflare rule list details are gathered
  tags:
    - rule_list_info
  ansible.builtin.uri:
    follow_redirects: false
    headers:
      Authorization: "Bearer {{ cf_auth_token }}"
    method: GET
    status_code:
      - 200
      - 401
      - 403
    url: "{{ 'https://api.cloudflare.com/client/v4/accounts/' +
             cf_account_id +
             '/rules/lists' }}"
  register: _rule_lists
  when:
    - cf_account_id is not none
    - cf_auth_token is not none

- name: Ensure dictionary of cloudflare rule lists is generated
  tags:
    - rule_list_info
  ansible.builtin.set_fact:
    _cf_rule_list_id: "{{ _cf_rule_list_id |
                          default({}) |
                          combine({_name: _id}) }}"
    _cf_rule_list_kind: "{{ _cf_rule_list_kind |
                            default({}) |
                            combine({_name: _kind}) }}"
    _cf_rule_list_items: "{{ _cf_rule_list_items |
                             default({}) |
                             combine({_name: _items}) }}"
    _cf_rule_list_referencing_filters: "{{ _cf_rule_list_referencing_filters |
                                           default({}) |
                                           combine({_name: _referencing_filters}) }}"
  loop: "{{ _rule_lists.json.result | d([], true) }}"
  loop_control:
    label: "{{ _list.name | default(none) }}"
    loop_var: _list
  vars:
    _id: "{{ _list.id }}"
    _name: "{{ _list.name }}"
    _items: "{{ _list.num_items | default(none) }}"
    _kind: "{{ _list.kind | default(none) }}"
    _referencing_filters: "{{ _list.num_referencing_filters | default(none) }}"
  when:
    - _list.id is defined
    - _list.name is defined
...
