---
- name: Ensure cloudflare zones information is gathered
  tags:
    - zones_info
  linuxhq.cloudflare.zones_info:
    api_token: "{{ zones_info_api_token }}"
    match: "{{ zones_info_match }}"
    page: "{{ zones_info_page }}"
    per_page: "{{ zones_info_per_page }}"
  register: __zones_info_query
  when:
    - zones_info_api_token is not none

- name: Ensure list of cloudflare zones information is generated
  tags:
    - zones_info
  ansible.builtin.set_fact:
    _zones_info_list:
      "{{ __zones_info_query.zones |
          d([]) }}"

- name: Ensure dict of cloudflare zones information is generated
  tags:
    - zones_info
  ansible.builtin.set_fact:
    _zones_info_dict:
      "{{ (dict(_zones_info_list |
               json_query('[].name') |
               zip(_zones_info_list))) |
          d({}) }}"
...
