---
- name: Ensure cloudflare access policies information is gathered
  tags:
    - access_policies_info
  linuxhq.cloudflare.access_policies_info:
    account_id: "{{ access_policies_info_account_id }}"
    api_token: "{{ access_policies_info_api_token }}"
  register: __access_policies_info_query
  when:
    - access_policies_info_account_id is not none
    - access_policies_info_api_token is not none

- name: Ensure list of cloudflare access policies information is generated
  tags:
    - access_policies_info
  ansible.builtin.set_fact:
    _access_policies_info_list:
      "{{ __access_policies_info_query.access_policies |
          d([]) }}"

- name: Ensure dict of cloudflare access policies information is generated
  tags:
    - access_policies_info
  ansible.builtin.set_fact:
    _access_policies_info_dict:
      "{{ (dict(_access_policies_info_list |
               json_query('[].name') |
               zip(_access_policies_info_list))) |
          d({}) }}"
...
