---
- name: Ensure cloudflare warp connectors are batched
  tags:
    - warp_connector
  ansible.builtin.include_tasks:
    apply:
      tags:
        - warp_connector
    file: include.yml
  loop:
    "{{ warp_connector_list |
        batch(warp_connector_batch) }}"
  loop_control:
    label: "{{ __warp_connector_list | length }}"
    loop_var: __warp_connector_list
...
