---
- name: Ensure cloudflare rulesets resources are batched
  tags:
    - rulesets
  ansible.builtin.include_tasks:
    apply:
      tags:
        - rulesets
    file: include.yml
  loop:
    "{{ rulesets_list |
        batch(rulesets_batch) }}"
  loop_control:
    label: "{{ __rulesets_list | length }}"
    loop_var: __rulesets_list
...
