---
- name: Ensure cloudflare cfd tunnels are managed
  tags:
    - cfd_tunnel
  linuxhq.cloudflare.cfd_tunnel:
    account_id: "{{ cfd_tunnel_account_id }}"
    api_token: "{{ cfd_tunnel_api_token }}"
    config_src: "{{ _cfd_tunnel.config_src | d(omit) }}"
    name: "{{ _cfd_tunnel.name }}"
    state: "{{ _cfd_tunnel.state | d('present') }}"
    tunnel_secret: "{{ _cfd_tunnel.tunnel_secret | d(omit) }}"
  register: __cfd_tunnel_result
  loop: "{{ __cfd_tunnel_list }}"
  loop_control:
    label: "{{ _cfd_tunnel.name | d(none) }}"
    loop_var: _cfd_tunnel
  async: "{{ ansible_check_mode | ternary(0, cfd_tunnel_async) }}"
  poll: "{{ cfd_tunnel_poll }}"
  when:
    - cfd_tunnel_account_id is not none
    - cfd_tunnel_api_token is not none
    - _cfd_tunnel.name is defined
  changed_when:
    - ansible_check_mode | bool
    - __cfd_tunnel_result.changed | bool

- name: Ensure managed cloudflare cfd tunnel jobs are complete
  tags:
    - cfd_tunnel
  ansible.builtin.async_status:
    jid: "{{ _jid.ansible_job_id }}"
  register: __cfd_tunnel_status
  loop: "{{ __cfd_tunnel_result.results }}"
  loop_control:
    label: "{{ _jid._cfd_tunnel.name | d(none) }}"
    loop_var: _jid
  when:
    - _jid.ansible_job_id is defined
  until:
    - __cfd_tunnel_status.finished | bool
  retries: "{{ cfd_tunnel_retries }}"
  delay: "{{ cfd_tunnel_delay }}"
...
