---
- name: Ensure cloudflare cfd tunnels are batched
  tags:
    - cfd_tunnel
  ansible.builtin.include_tasks:
    apply:
      tags:
        - cfd_tunnel
    file: include.yml
  loop:
    "{{ cfd_tunnel_list |
        batch(cfd_tunnel_batch) }}"
  loop_control:
    label: "{{ __cfd_tunnel_list | length }}"
    loop_var: __cfd_tunnel_list
...
