---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        account_info_account_name: "{{ lookup('env', 'CLOUDFLARE_ACCOUNT_NAME') }}"
        account_info_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"

verifier:
  name: ansible
  options:
    diff: true
...
