---
- name: Ensure cloudflare dnssec settings are batched
  tags:
    - dnssec
  ansible.builtin.include_tasks:
    apply:
      tags:
        - dnssec
    file: include.yml
  loop:
    "{{ dnssec_list |
        batch(dnssec_batch) }}"
  loop_control:
    label: "{{ __dnssec_list | length }}"
    loop_var: __dnssec_list
...
