---
- name: Ensure cloudflare access group details are gathered
  tags:
    - access_group
  ansible.builtin.uri:
    follow_redirects: false
    headers:
      Authorization: "Bearer {{ cf_auth_token }}"
    method: GET
    status_code:
      - 200
    url: "{{ 'https://api.cloudflare.com/client/v4/accounts/' +
             cf_account_id +
             '/access/groups' }}"
  register: _access_group_get
  when:
    - cf_account_id is not none
    - cf_auth_token is not none

- name: Ensure dictionary of access group ids is generated
  tags:
    - access_group
  ansible.builtin.set_fact:
    _cf_groups: "{{ _cf_groups |
                    default({}) |
                    combine({_name: _id}) }}"
  loop: "{{ _access_group_get.json.result }}"
  loop_control:
    label: "{{ _name | default(none) }}"
    loop_var: _group
  vars:
    _name: "{{ _group.name }}"
    _id: "{{ _group.id }}"
  when:
    - _access_group_get.json.result is defined
    - _access_group_get.json.result | length > 0
    - _group.id is defined
    - _group.name is defined

- name: Ensure cloudflare access groups are present
  tags:
    - access_group
  ansible.builtin.uri:
    body:
      exclude: "{{ _group.exclude | default(omit) }}"
      include: "{{ _group.include }}"
      is_default: "{{ _group.is_default | default(false) }}"
      name: "{{ _group.name }}"
      require: "{{ _group.require | default(omit) }}"
    body_format: json
    follow_redirects: false
    headers:
      Authorization: "Bearer {{ cf_auth_token }}"
    method: POST
    status_code:
      - 201
    url: "{{ 'https://api.cloudflare.com/client/v4/accounts/' +
             cf_account_id +
             '/access/groups' }}"
  loop: "{{ cf_access_groups }}"
  loop_control:
    label: "{{ _group.name | default(none) }}"
    loop_var: _group
  when:
    - cf_account_id is not none
    - cf_auth_token is not none
    - _group.include is defined
    - _group.name is defined
    - _cf_groups is not defined or
      _group.name not in _cf_groups.keys()

- name: Ensure cloudflare access groups are updated
  tags:
    - access_group
  ansible.builtin.uri:
    body:
      exclude: "{{ _group.exclude | default(omit) }}"
      include: "{{ _group.include }}"
      is_default: "{{ _group.is_default | default(false) }}"
      name: "{{ _group.name }}"
      require: "{{ _group.require | default(omit) }}"
    body_format: json
    follow_redirects: false
    headers:
      Authorization: "Bearer {{ cf_auth_token }}"
    method: PUT
    status_code:
      - 200
    url: "{{ 'https://api.cloudflare.com/client/v4/accounts/' +
             cf_account_id +
             '/access/groups/' +
             _cf_groups[_group.name] }}"
  loop: "{{ cf_access_groups }}"
  loop_control:
    label: "{{ _group.name | default(none) }}"
    loop_var: _group
  when:
    - cf_account_id is not none
    - cf_auth_token is not none
    - _group.include is defined
    - _group.name is defined
    - _cf_groups is defined and
      _group.name in _cf_groups.keys()
...
