---
- name: Ensure cloudflare cache purges are batched
  tags:
    - purge_cache
  ansible.builtin.include_tasks:
    apply:
      tags:
        - purge_cache
    file: include.yml
  loop:
    "{{ purge_cache_list |
        batch(purge_cache_batch) }}"
  loop_control:
    label: "{{ __purge_cache_list | length }}"
    loop_var: __purge_cache_list
...
