---
- name: Verify
  hosts: all

  roles:
    - zones_info

  post_tasks:
    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        rulesets_list:
          "{{ rulesets_list |
              map('combine', {'state': 'absent'}) }}"
        zones_list:
          "{{ zones_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - rulesets
        - zones
      loop_control:
        label: "{{ _role | d(none) }}"
        loop_var: _role
...
