---
- name: Ensure cloudflare dns records are batched
  tags:
    - dns
  ansible.builtin.include_tasks:
    apply:
      tags:
        - dns
    file: include.yml
  loop:
    "{{ q('ansible.builtin.subelements',
          dns_records,
          'records',
          {'skip_missing': true}) |
        batch(dns_batch) }}"
  loop_control:
    label: "{{ __dns_records | length }}"
    loop_var: __dns_records
...
