---
- name: Ensure cloudflare dnssec information is gathered
  tags:
    - dnssec_info
  linuxhq.cloudflare.dnssec_info:
    api_token: "{{ dnssec_info_api_token }}"
  register: __dnssec_info_query
  when:
    - dnssec_info_api_token is not none

- name: Ensure list of cloudflare dnssec information is generated
  tags:
    - dnssec_info
  ansible.builtin.set_fact:
    _dnssec_info_list:
      "{{ __dnssec_info_query.dnssec |
          d([]) }}"

- name: Ensure dict of cloudflare dnssec information is generated
  tags:
    - dnssec_info
  ansible.builtin.set_fact:
    _dnssec_info_dict:
      "{{ (dict(_dnssec_info_list |
                json_query('[].name') |
                zip(_dnssec_info_list))) |
          d({}) }}"
...
