---
- name: Ensure cloudflare pages domains are present
  tags:
    - pages_domain
  ansible.builtin.uri:
    body:
      name: "{{ _domain.name }}"
    body_format: json
    follow_redirects: false
    headers:
      Authorization: "Bearer {{ cf_auth_token }}"
    method: POST
    status_code:
      - 200
      - 400
    url: "{{ 'https://api.cloudflare.com/client/v4/accounts/' +
             cf_account_id +
             '/pages/projects/' +
             _domain.project_name +
             '/domains' }}"
  register: _domains_post
  loop: "{{ cf_pages_domains }}"
  loop_control:
    label: "{{ _domain.project_name | default(none) }}"
    loop_var: _domain
  when:
    - cf_account_id is not none
    - cf_auth_token is not none
    - _domain.name is defined
    - _domain.project_name is defined

- name: Ensure cloudflare pages domains are patched
  tags:
    - pages_domain
  ansible.builtin.uri:
    follow_redirects: false
    headers:
      Authorization: "Bearer {{ cf_auth_token }}"
    method: PATCH
    status_code:
      - 200
    url: "{{ 'https://api.cloudflare.com/client/v4/accounts/' +
             cf_account_id +
             '/pages/projects/' +
             _project +
             '/domains/' +
             _domain }}"
  loop: "{{ _domains_post.results }}"
  loop_control:
    label: "{{ _domain | default(none) }}"
    loop_var: _patch
  vars:
    _domain: "{{ _patch._domain.name }}"
    _project: "{{ _patch._domain.project_name }}"
  when:
    - cf_account_id is not none
    - cf_auth_token is not none
    - _domains_post.results | length > 0
    - _patch.status == 400
    - _patch._domain.name is defined
    - _patch._domain.project_name is defined
...
