---
- name: Ensure cloudflare rulesets information is gathered
  tags:
    - rulesets_info
  linuxhq.cloudflare.rulesets_info:
    api_token: "{{ rulesets_info_api_token }}"
    phase: "{{ rulesets_info_phase }}"
  register: __rulesets_info_query
  when:
    - rulesets_info_api_token is not none

- name: Ensure list of cloudflare rulesets information is generated
  tags:
    - rulesets_info
  ansible.builtin.set_fact:
    _rulesets_info_list:
      "{{ __rulesets_info_query.rulesets |
          d([]) }}"

- name: Ensure dict of cloudflare rulesets information is generated
  tags:
    - rulesets_info
  ansible.builtin.set_fact:
    _rulesets_info_dict:
      "{{ (dict(_rulesets_info_list |
               json_query('[].name') |
               zip(_rulesets_info_list))) |
          d({}) }}"
...
