---
dependencies: []
galaxy_info:
  role_name: zone_info
  author: Taylor Kimball
  description: Gather information about cloudflare zones
  license: GPLv3
  min_ansible_version: 8.0
  platforms:
    - name: Cloudflare
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - info
    - zone
...
