---
allow_duplicates: true
dependencies: []
galaxy_info:
  role_name: zone_info
  author: Taylor Kimball
  description: Gather information about cloudflare zones
  license: GPLv3
  min_ansible_version: 2.15.0
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - info
    - zone
...
