---
dependencies: []
galaxy_info:
  role_name: zone_info
  author: Taylor Kimball
  description: Gather information about cloudflare zones
  license: GPLv3
  min_ansible_version: 2.14.0
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - cloudflare
    - info
    - zone
...
