---
dependencies:
  - { role: linuxhq.cloudflare.zone_info, tags: network }
galaxy_info:
  role_name: network
  author: Taylor Kimball
  description: Configure network settings
  license: GPLv3
  min_ansible_version: 2.15.0
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - network
...
