---
- name: Ensure cloudflare access groups are batched
  tags:
    - access_groups
  ansible.builtin.include_tasks:
    apply:
      tags:
        - access_groups
    file: include.yml
  loop:
    "{{ access_groups_list |
        batch(access_groups_batch) }}"
  loop_control:
    label: "{{ __access_groups_list | length }}"
    loop_var: __access_groups_list
...
