---
- name: Verify
  hosts: all
  roles:
    - zones_info

  post_tasks:
    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _zones_info_dict[_item].account.id is defined
          - _zones_info_dict[_item].account.name is defined
          - _zones_info_dict[_item].id is defined
          - _zones_info_dict[_item].name is defined
          - _zones_info_dict[_item].name_servers | length == 2
          - _zones_info_dict[_item].status is defined
          - _zones_info_dict[_item].type == 'full'
      loop:
        "{{ zones_list |
            map(attribute='name', default=[]) }}"
      loop_control:
        label: "{{ _item | d(none) }}"
        loop_var: _item

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        zones_list:
          "{{ zones_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - zones
      loop_control:
        label: "{{ _role | d(none) }}"
        loop_var: _role
...
