---
- name: Verify
  hosts: all

  roles:
    - access_service_tokens_info

  post_tasks:
    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        access_groups_list:
          "{{ access_groups_list |
              map('combine', {'state': 'absent'}) }}"
        access_service_tokens_list:
          "{{ access_service_tokens_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - access_groups
        - access_service_tokens
      loop_control:
        label: "{{ _role | d(none) }}"
        loop_var: _role
...
