---
- name: Ensure cloudflare zones resources are batched
  tags:
    - zones
  ansible.builtin.include_tasks:
    apply:
      tags:
        - zones
    file: include.yml
  loop:
    "{{ zones_list |
        batch(zones_batch) }}"
  loop_control:
    label: "{{ __zones_list | length }}"
    loop_var: __zones_list
...
