---
- name: Ensure cloudflare access apps information is gathered
  tags:
    - access_apps_info
  linuxhq.cloudflare.access_apps_info:
    account_id: "{{ access_apps_info_account_id }}"
    api_token: "{{ access_apps_info_api_token }}"
  register: __access_apps_info_query
  when:
    - access_apps_info_account_id is not none
    - access_apps_info_api_token is not none

- name: Ensure list of cloudflare access apps information is generated
  tags:
    - access_apps_info
  ansible.builtin.set_fact:
    _access_apps_info_list:
      "{{ __access_apps_info_query.access_apps |
          d([]) }}"

- name: Ensure dict of cloudflare access apps information is generated
  tags:
    - access_apps_info
  ansible.builtin.set_fact:
    _access_apps_info_dict:
      "{{ (dict(_access_apps_info_list |
               json_query('[].name') |
               zip(_access_apps_info_list))) |
          d({}) }}"
...
