---
- name: Ensure cloudflare zerotrust connectivity settings are managed
  tags:
    - zerotrust_connectivity_settings
  linuxhq.cloudflare.zerotrust_connectivity_settings:
    account_id: "{{ zerotrust_connectivity_settings_account_id }}"
    api_token: "{{ zerotrust_connectivity_settings_api_token }}"
    icmp_proxy_enabled: "{{ zerotrust_connectivity_settings_icmp_proxy_enabled }}"
    offramp_warp_enabled: "{{ zerotrust_connectivity_settings_offramp_warp_enabled }}"
  when:
    - zerotrust_connectivity_settings_account_id is not none
    - zerotrust_connectivity_settings_api_token is not none
...
