---
- name: Verify
  hosts: all

  tasks:
    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        rules_lists_list:
          "{{ rules_lists_list_update |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - rules_lists
      loop_control:
        label: "{{ _role | d(none) }}"
        loop_var: _role
...
