---
- name: Ensure cloudflare pagerules information is gathered
  tags:
    - pagerules_info
  linuxhq.cloudflare.pagerules_info:
    api_token: "{{ pagerules_info_api_token }}"
  register: __pagerules_info_query
  when:
    - pagerules_info_api_token is not none

- name: Ensure list of cloudflare pagerules information is generated
  tags:
    - pagerules_info
  ansible.builtin.set_fact:
    _pagerules_info_list:
      "{{ __pagerules_info_query.pagerules |
          d([]) }}"

- name: Ensure dict of cloudflare pagerules information is generated
  tags:
    - pagerules_info
  ansible.builtin.set_fact:
    _pagerules_info_dict:
      "{{ (dict(_pagerules_info_list |
                json_query('[].name') |
                zip(_pagerules_info_list))) |
          d({}) }}"
...
