---
- name: Converge
  hosts: all
  roles:
    - role: zones
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: dnssec
      dnssec_list: []
      tags:
        - molecule-idempotence-notest

    - dnssec
...
