---
- name: Ensure cloudflare accounts information is gathered
  tags:
    - accounts_info
  linuxhq.cloudflare.accounts_info:
    api_token: "{{ accounts_info_api_token }}"
    name: "{{ accounts_info_name }}"
  register: __accounts_info_query
  when:
    - accounts_info_api_token is not none
    - accounts_info_name is not none

- name: Ensure cloudflare accounts information is generated
  tags:
    - accounts_info
  ansible.builtin.set_fact:
    _accounts_info_id: "{{ __accounts_info_query.account.id }}"
    _accounts_info_name: "{{ __accounts_info_query.account.name }}"
    _accounts_info_settings: "{{ __accounts_info_query.account.settings }}"
    _accounts_info_type: "{{ __accounts_info_query.account.type }}"
  when:
    - __accounts_info_query.account is defined
    - __accounts_info_query.account.name is defined
    - __accounts_info_query.account.id is defined
    - __accounts_info_query.account.settings is defined
    - __accounts_info_query.account.type is defined
...
