---
- name: Ensure cloudflare access service tokens information is gathered
  tags:
    - access_service_tokens_info
  linuxhq.cloudflare.access_service_tokens_info:
    account_id: "{{ access_service_tokens_info_account_id }}"
    api_token: "{{ access_service_tokens_info_api_token }}"
  register: __access_service_tokens_info_query
  when:
    - access_service_tokens_info_account_id is not none
    - access_service_tokens_info_api_token is not none

- name: Ensure list of cloudflare access service tokens information is generated
  tags:
    - access_service_tokens_info
  ansible.builtin.set_fact:
    _access_service_tokens_info_list:
      "{{ __access_service_tokens_info_query.service_tokens |
          d([]) }}"

- name: Ensure dict of cloudflare access service tokens information is generated
  tags:
    - access_service_tokens_info
  ansible.builtin.set_fact:
    _access_service_tokens_info_dict:
      "{{ (dict(_access_service_tokens_info_list |
               json_query('[].name') |
               zip(_access_service_tokens_info_list))) |
          d({}) }}"
...
