---
name: ansible-galaxy
'on':
  push:
    tags:
      - '*'

jobs:
  ansible-galaxy:
    name: ansible-galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Ensure codebase is present
        uses: actions/checkout@v2

      - name: Ensure python3 is present
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Ensure ansible-core is present
        run: pip install ansible-core==2.14.0

      - name: Ensure ansible-galaxy collection is built
        run: ansible-galaxy collection build

      - name: Ensure ansible-galaxy collection is published
        run: ansible-galaxy collection publish --api-key ${{ secrets.GALAXY_API_KEY }} linuxhq-cloudflare-*.tar.gz
...
