---
name: sanity
'on':
  push:
    branches: '**'
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  sanity:
    name: sanity (${{ matrix.ansible }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ansible: 'ansible-core==2.18.*'
            python: '3.12'
          - ansible: 'ansible>14,<15'
            python: '3.13'
    defaults:
      run:
        working-directory: ansible_collections/linuxhq/cloudflare
    steps:
      - uses: actions/checkout@v4
        with:
          path: ansible_collections/linuxhq/cloudflare
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python }}"
      - run: pip install '${{ matrix.ansible }}'
      - run: ansible-test sanity --requirements --color -v
